import praw
import config
import random
import time
import os
def bot_login():
    r = praw.Reddit(username = config.username,
            password = config.password,
            client_id = config.client_id,
            client_secret = config.client_secret,
            user_agent = "created by farrygodjd to comment")
    return r
keywords = ['Aragorn' , 'aragorn' , 'Gondor' , 'gondor' , 'Ranger' , 'ranger' , 'dunedain' , 'Dunedain']

def run_bot(r, comment_replied_to):
    for comment in r.subreddit('lotrmemes').comments(limit=25):
        for keyword in keywords:
            if keyword in comment.body and comment.id not in comment_replied_to and not comment.author == r.user.me:
                print( "aragorn has been found")
                list = ['[I WOULD HAVE GONE WITH YOU TO THE END INTO THE VERY FIRES OF MORDOR!](https://www.youtube.com/watch?v=F2S2GCqCFTA)',
                        '[NOT IF WE HOLD TRUE TO EACH OTHER!](https://www.youtube.com/watch?v=MQcfsB0vyak)', '[I THOUGHT I HAD WANDERED INTO A DREAM!](https://www.youtube.com/watch?v=6jvNTLSIcAM)',
                        '[I WILL NOT LET THE WHITE CITY FALL NOR OUR PEOPLE FAIL!](https://www.youtube.com/watch?v=V5iPWmNhR28)', '[FOR FRODO!!](https://www.youtube.com/watch?v=ufhcNPXD9Hc)',
                        '[IF BY MY LIFE OR DEATH I CAN PROTECT YOU I WILL!](https://www.youtube.com/watch?v=hyquiA8RL1Q)',
                        '[YOU HAVE MY SWORD!](https://www.youtube.com/watch?v=hyquiA8RL1Q)', '[I DO NOT FEAR DEATH!](https://www.youtube.com/watch?v=r2vYRQlS2aQ)',
                        '[MY FRIENDS YOU BOW TO NO ONE!](https://www.youtube.com/watch?v=13J1mAGNUls)' , 'BUT I MUST ADMIT THAT I HOPED YOU WOULD TAKE TO ME FOR MY OWN SAKE. A HUNTED MAN SOMETIMES WEARIES OF DISTRUST AND LONGS FOR FRIENDSHIP. BUT THERE, I BELIEVE MY LOOKS ARE AGAINST ME.!' , 'FOR MY PART I FORGIVE YOUR DOUBT. LITTLE DO I RESEMBLE THE FIGURES OF ELENDIL AND ISILDUR AS THEY STAND CARVEN IN THIER MAJESTY IN THE HALLS OF DENETHOR. I AM BUT A HEIR OF ISILDUR, NOT ISILDUR HIMSELF. I HAVE HAD A HARD LIFE AND AND A LONG; AND THE LEAGUES THAT LIE BETWEEN HERE AND GONDOR ARE A SMALL PART IN THE COUNT OF MY JOURNEYS. I HAVE CROSSED MANY MOUNTAINS AND MANY RIVERS AND TRODDEN MANY PLAINS EVER INTO THE FAR COUNTRIES OF RHUN AND HARAD WHERE WHERE THE STARS ARE STRANGE!' ,
                        '[STAND YOUR GROUND, SONS OF GONDOR OF ROHAN MY BROTHERS. I SEE IN YOUR EYES THE SAME FEAR THAT WOULD TAKE THE HEART OF ME! A DAY MAY COME WHEN THE COURAGE OF MEN FAILS WHEN WE FORSAKE OUR FRIENDS AND BREAK ALL BONDS OF FELLOWSHIP BUT IT IS NOT THIS DAY!AN HOUR OF WOLVES AND SHATTERD SHIELDS WHEN THE AGE OF MEN COMES CRASHING DOWN BUT IT IS NOT THIS DAY, THIS DAY WE FIGHT!!! AND FOR ALL THAT IS DEAR TO YOU IN THIS WORLD I BID YOU STAND MEN OF THE WEST AND FIGHT!!!](https://www.youtube.com/watch?v=SwMUY5ro5Xo) ' ,
                        '[RIDE OUT WITH ME. RIDE OUT AND MEET THEM.](https://www.youtube.com/watch?v=kzvAAAHVFBI)' , 'LONELY MEN ARE WE RANGERS OF THE WILD. HUNTERS – BUT HUNTERS EVER OF THE SERVANTS OF THE ENEMY; FOR THEY ARE FOUND IN MANY PLACES NOT IN MORDOR ONLY. ”STRIDER” AM I TO ONE FAT MAN WHO LIVES WITHIN A DAY´S MARCH OF FOES THAT WOULD FREEZE HIS HEART OR LAY HIS LITTLE TOWN IN RUIN IF HE WERE NOT GUARDED CEASELESSLY. YET WE WOULD NOT HAVE IT OTHERWISE. IF SIMPLE FOLK ARE FREE FROM CARE AND FEAR, SIMPLE THEY WILL BE AND WE MUST BE SECRET TO KEEP THEM SO. THAT HAS BEEN THE TASK OF MY KINDRED WHILE THE YEARS HAVE LENGTHENED AND THE GRASS HAS GROWN.' , '[War is upon you whether you risk it or not](https://www.youtube.com/watch?v=RaBdoLVJQag)' , '[NOT IF WE HOLD TRUE TO EACH OTHER. WE WILL NOT ABANDON MERRY AND PIPPIN TO TORMENT AND DEATH. NOT WHILE WE HAVE STRENGTH LEFT. LEAVE ALL THAT CAN BE SPARED BEHIND. WE TRAVEL LIGHT. LET’S HUNT SOME ORC !](https://www.youtube.com/watch?v=MQcfsB0vyak)' ,
                        '[I AM ISILDUR’S HEIR. FIGHT FOR ME! AND I WILL HOLD YOUR OATH FULFILLED! WHAT SAY YOU!?](https://www.youtube.com/watch?v=r622O7Kh4B4)' , '[You will suffer me](https://www.youtube.com/watch?v=r622O7Kh4B4)' ,
                        'A HUNTED MAN SOMETIMES WEARIES OF DISTRUST AND LONGS FOR FRIENDSHIP. BUT THERE I BELIEVE MY LOOKS ARE AGAINST ME!' , '[BE AT PEACE SON OF GONDOR!!](https://www.youtube.com/watch?v=zcHhlcxUkP4)' ,
                        'I WOULD HAVE GUIDED FRODO TO MORDOR AND GONE WITH HIM TO THE END!' , '[I DO NOT WANT THAT POWER. I HAVE NEVER WANTED IT!](https://www.youtube.com/watch?v=V1c2tUcL-jY)' , '[LET US TOGETHER REBUILD THIS WORLD THAT WE MAY SHARE IN THE DAYS OF PEACE!](https://www.youtube.com/watch?v=W6t9OF8_3n8)' ,
                        'THE BEST REVENGE IS LETTING GO AND LIVING WELL!' , 'TIS THE LAY OF LUTHIEN. THE ELF-MAIDEN WHO GAVE HER LOVE TO BEREN A MORTAL!' , '[HES TRYING TO BRING DOWN THE MOUNTAIN! GANDALF WE MUST TURN BACK!](https://www.youtube.com/watch?v=YH4Xr6GIp4U)' ,
                        '[I SWORE TO PROTECT YOU!](https://www.dailymotion.com/video/x4c1g1z)' , '[THE BEACONS OF MINAS TIRITH! THE BEACONS ARE LIT! GONDOR CALLS FOR AID!](https://www.youtube.com/watch?v=QhRFaY8A9cA)' , '[IT IS BUT A SHADOW AND A THOUGHT THAT YOU LOVE. I CANNOT GIVE YOU WHAT YOU SEEK](https://www.youtube.com/watch?v=KHLXGwjpVqw)' , ' [SAURON WILL NOT HAVE FORGOTTEN THE SWORD OF ELENDIL. THE BLADE THAT WAS BROKEN SHALL RETURN TO MINAS TIRITH!](https://www.youtube.com/watch?v=fsbDigj7w5c)' ,
                        '[MURDERERS. TRAITORS. YOU WOULD CALL UPON THEM TO FIGHT? THEY BELIEVE IN NOTHING. THEY ANSWER TO NO ONE.](https://www.youtube.com/watch?v=fsbDigj7w5c)' , '[IF SAURON HAD THE RING WE WOULD KNOW IT!](https://www.youtube.com/watch?v=ynftPM-OB7o)' ,
                        '[NO. THERE IS STILL HOPE FOR FRODO. HE NEEDS TIME... AND SAFE PASSAGE ACROSS THE PLAINS OF GORGOROTH. WE CAN GIVE HIM THAT.](https://www.youtube.com/watch?v=ynftPM-OB7o)' , '[DRAW OUT SAURONS ARMIES. EMPTY HIS LANDS. THEN WE GATHER OUR FULL STRENGTH AND MARCH ON THE BLACK GATE!](https://www.youtube.com/watch?v=ynftPM-OB7o)' ,
                        '[HOLD YOUR GROUND, HOLD YOUR GROUND. SONS OF GONDOR, OF ROHAN MY BROTHERS. I SEE IN YOUR EYES THE SAME FEAR THAT WOULD TAKE THE HEART OF ME. A DAY MAY COME WHEN THE COURAGE OF MEN FAILS WHEN WE FORSAKE OUR FRIENDS AND BREAK ALL BONDS OF FELLOWSHIP BUT IT IS NOT THIS DAY. AN HOUR OF WOES AND SHATTERED SHIELDS WHEN THE AGE OF MEN COMES CRASHING DOWN BUT IT IS NOT THIS DAY. THIS DAY WE FIGHT! BY ALL THAT YOU HOLD DEAR ON THIS GOOD EARTH I BID YOU STAND, MEN OF THE WEST!](https://www.youtube.com/watch?v=_MsRcq9rvTQ)' ,
                        '[Let the lord of the Black Lands come forth, that justice be done upon him!](https://www.youtube.com/watch?v=To_RJ_mPNqM)' , ' [We have time. Every day Frodo moves closer to Mordor.](https://www.youtube.com/watch?v=altXWl6JO18)' , ' [THEN I SHALL DIE AS ONE OF THEM!](https://www.youtube.com/watch?v=W8BhTlPZAoM)' , 'MY LADY, THERE MAY COME A TIME FOR VALOR WITHOUT RENOWN. WHO THEN WILL YOUR PEOPLE LOOK TO IN THE LAST DEFENSE?' ,
                        '[YOU HAVE SOME SKILL WITH A BLADE](https://www.dailymotion.com/video/x4c8xy5)' , '[YOU ARE A DAUGHTER OF KINGS A SHIELD MAIDEN OF ROHAN. I DO NOT THINK THAT WILL BE YOUR FATE!](https://www.youtube.com/watch?v=MTGnbIip_TU)' , '[THEY DO NOT COME TO DESTROY ROHANS CROPS OR VILLAGES. THEY COME TO DESTROY ITS PEOPLE. DOWN TO THE LAST CHILD.](https://www.youtube.com/watch?v=RSYX4ckG4tw)' , '[ITS THE BEARDS!](https://www.youtube.com/watch?v=d-PmAQ9Opu4)' ,
                        '[OPEN WAR IS UPON YOU WHETHER YOU WOULD RISK IT OR NOT!](https://www.youtube.com/watch?v=RaBdoLVJQag)' , '[FARMERS, FERRIERS, STABLE BOYS. THESE ARE NO SOLDIERS.](https://www.youtube.com/watch?v=W8BhTlPZAoM)' , ' [IT IS AN ARMY BRED FOR A SINGLE PURPOSE, TO DESTROY THE WORLD OF MEN. THEY WILL BE HERE BY NIGHTFALL.](https://www.youtube.com/watch?v=VjxpAOIAsns)' ,
                        'THEY WERE ONCE MEN. GREAT KINGS OF MEN. THEN SAURON THE DECEIVER GAVE TO THEM NINE RINGS OF POWER. BLINDED BY THEIR GREED, THEY TOOK THEM WITHOUT QUESTION, ONE BY ONE FALLING INTO DARKNESS. NOW THEY ARE SLAVES TO HIS WILL. THEY ARE THE NAZGUL, RINGWRAITHS, NEITHER LIVING NOR DEAD. AT ALL TIMES THEY FEEL THE PRESENCE OF THE RING, DRAWN TO THE POWER OF THE ONE. THEY WILL NEVER STOP HUNTING YOU.']
                random_item = random.choice(list)
                comment.reply(random_item)
                comment_replied_to.append(comment.id)

                with open("comment_replied_to.txt", "a") as f:
                    f.write(comment.id + "\n")
    print("sleeping for 10 seconds")
    time.sleep(10)
def run_bot(r, comment_replied_to):
    for comment in r.subreddit('lotr').comments(limit=25):
        for keyword in keywords:
            if "!Aragorn-bot" in comment.body and comment.id not in comment_replied_to and not comment.author == r.user.me:
                print( "aragorn has been found")
                list = ['I WOULD HAVE GONE WITH YOU TO THE END INTO THE VERY FIRES OF MORDOR!',
                        'NOT IF WE HOLD TRUE TO EACH OTHER!', 'I THOUGHT I HAD WANDERED INTO A DREAM!',
                        'I WILL NOT LET THE WHITE CITY FALL NOR OUR PEOPLE FAIL!', 'FOR FRODO!!',
                        'IF BY MY LIFE OR DEATH I CAN PROTECT YOU I WILL!',
                        'YOU HAVE MY SWORD!', 'I DO NOT FEAR DEATH!', 'MY FRIENDS YOU BOW TO NO ONE!' , 'BUT I MUST ADMIT THAT I HOPED YOU WOULD TAKE TO ME FOR MY OWN SAKE. A HUNTED MAN SOMETIMES WEARIES OF DISTRUST AND LONGS FOR FRIENDSHIP. BUT THERE, I BELIEVE MY LOOKS ARE AGAINST ME.!' , 'FOR MY PART I FORGIVE YOUR DOUBT. LITTLE DO I RESEMBLE THE FIGURES OF ELENDIL AND ISILDUR AS THEY STAND CARVEN IN THIER MAJESTY IN THE HALLS OF DENETHOR. I AM BUT A HEIR OF ISILDUR, NOT ISILDUR HIMSELF. I HAVE HAD A HARD LIFE AND AND A LONG; AND THE LEAGUES THAT LIE BETWEEN HERE AND GONDOR ARE A SMALL PART IN THE COUNT OF MY JOURNEYS. I HAVE CROSSED MANY MOUNTAINS AND MANY RIVERS AND TRODDEN MANY PLAINS EVER INTO THE FAR COUNTRIES OF RHUN AND HARAD WHERE WHERE THE STARS ARE STRANGE!' ,
                        'STAND YOUR GROUND, SONS OF GONDOR OF ROHAN MY BROTHERS. I SEE IN YOUR EYES THE SAME FEAR THAT WOULD TAKE THE HEART OF ME! A DAY MAY COME WHEN THE COURAGE OF MEN FAILS WHEN WE FORSAKE OUR FRIENDS AND BREAK ALL BONDS OF FELLOWSHIP BUT IT IS NOT THIS DAY!AN HOUR OF WOLVES AND SHATTERD SHIELDS WHEN THE AGE OF MEN COMES CRASHING DOWN BUT IT IS NOT THIS DAY, THIS DAY WE FIGHT!!! AND FOR ALL THAT IS DEAR TO YOU IN THIS WORLD I BID YOU STAND MEN OF THE WEST AND FIGHT!!! ' ,
                        'RIDE OUT WITH ME. RIDE OUT AND MEET THEM.' , 'LONELY MEN ARE WE RANGERS OF THE WILD. HUNTERS – BUT HUNTERS EVER OF THE SERVANTS OF THE ENEMY; FOR THEY ARE FOUND IN MANY PLACES NOT IN MORDOR ONLY. ”STRIDER” AM I TO ONE FAT MAN WHO LIVES WITHIN A DAY´S MARCH OF FOES THAT WOULD FREEZE HIS HEART OR LAY HIS LITTLE TOWN IN RUIN IF HE WERE NOT GUARDED CEASELESSLY. YET WE WOULD NOT HAVE IT OTHERWISE. IF SIMPLE FOLK ARE FREE FROM CARE AND FEAR, SIMPLE THEY WILL BE AND WE MUST BE SECRET TO KEEP THEM SO. THAT HAS BEEN THE TASK OF MY KINDRED WHILE THE YEARS HAVE LENGTHENED AND THE GRASS HAS GROWN.' , 'War is upon you whether you risk it or not' , 'NOT IF WE HOLD TRUE TO EACH OTHER. WE WILL NOT ABANDON MERRY AND PIPPIN TO TORMENT AND DEATH. NOT WHILE WE HAVE STRENGTH LEFT. LEAVE ALL THAT CAN BE SPARED BEHIND. WE TRAVEL LIGHT. LET’S HUNT SOME ORC !' ,
                        'I AM ISILDUR’S HEIR. FIGHT FOR ME! AND I WILL HOLD YOUR OATH FULFILLED! WHAT SAY YOU!?' , 'You will suffer me' ,
                        'A HUNTED MAN SOMETIMES WEARIES OF DISTRUST AND LONGS FOR FRIENDSHIP. BUT THERE I BELIEVE MY LOOKS ARE AGAINST ME!' , 'BE AT PEACE SON OF GONDOR!!' ,
                        'I WOULD HAVE GUIDED FRODO TO MORDOR AND GONE WITH HIM TO THE END!' , 'I DO NOT WANT THAT POWER. I HAVE NEVER WANTED IT!' , 'LET US TOGETHER REBUILD THIS WORLD THAT WE MAY SHARE IN THE DAYS OF PEACE!' ,
                        'THE BEST REVENGE IS LETTING GO AND LIVING WELL!' , 'TIS THE LAY OF LUTHIEN. THE ELF-MAIDEN WHO GAVE HER LOVE TO BEREN A MORTAL!' , 'HES TRYING TO BRING DOWN THE MOUNTAIN! GANDALF WE MUST TURN BACK!' ,
                        'I SWORE TO PROTECT YOU!' , 'THE BEACONS OF MINAS TIRITH! THE BEACONS ARE LIT! GONDOR CALLS FOR AID!' , 'IT IS BUT A SHADOW AND A THOUGHT THAT YOU LOVE. I CANNOT GIVE YOU WHAT YOU SEEK' , ' SAURON WILL NOT HAVE FORGOTTEN THE SWORD OF ELENDIL. THE BLADE THAT WAS BROKEN SHALL RETURN TO MINAS TIRITH!' ,
                        'MURDERERS. TRAITORS. YOU WOULD CALL UPON THEM TO FIGHT? THEY BELIEVE IN NOTHING. THEY ANSWER TO NO ONE.' , 'IF SAURON HAD THE RING WE WOULD KNOW IT!' ,
                        'NO. THERE IS STILL HOPE FOR FRODO. HE NEEDS TIME... AND SAFE PASSAGE ACROSS THE PLAINS OF GORGOROTH. WE CAN GIVE HIM THAT.' , 'DRAW OUT SAURONS ARMIES. EMPTY HIS LANDS. THEN WE GATHER OUR FULL STRENGTH AND MARCH ON THE BLACK GATE!' ,
                        'HOLD YOUR GROUND, HOLD YOUR GROUND. SONS OF GONDOR, OF ROHAN MY BROTHERS. I SEE IN YOUR EYES THE SAME FEAR THAT WOULD TAKE THE HEART OF ME. A DAY MAY COME WHEN THE COURAGE OF MEN FAILS WHEN WE FORSAKE OUR FRIENDS AND BREAK ALL BONDS OF FELLOWSHIP BUT IT IS NOT THIS DAY. AN HOUR OF WOES AND SHATTERED SHIELDS WHEN THE AGE OF MEN COMES CRASHING DOWN BUT IT IS NOT THIS DAY. THIS DAY WE FIGHT! BY ALL THAT YOU HOLD DEAR ON THIS GOOD EARTH I BID YOU STAND, MEN OF THE WEST!' ,
                        'Let the lord of the Black Lands come forth, that justice be done upon him!' , ' We have time. Every day Frodo moves closer to Mordor.' , ' THEN I SHALL DIE AS ONE OF THEM!' , 'MY LADY, THERE MAY COME A TIME FOR VALOR WITHOUT RENOWN. WHO THEN WILL YOUR PEOPLE LOOK TO IN THE LAST DEFENSE?' ,
                        'YOU HAVE SOME SKILL WITH A BLADE' , 'YOU ARE A DAUGHTER OF KINGS A SHIELD MAIDEN OF ROHAN. I DO NOT THINK THAT WILL BE YOUR FATE!' , 'THEY DO NOT COME TO DESTROY ROHANS CROPS OR VILLAGES. THEY COME TO DESTROY ITS PEOPLE. DOWN TO THE LAST CHILD.' , 'ITS THE BEARDS!' ,
                        'OPEN WAR IS UPON YOU WHETHER YOU WOULD RISK IT OR NOT!' , 'FARMERS, FERRIERS, STABLE BOYS. THESE ARE NO SOLDIERS.' , ' IT IS AN ARMY BRED FOR A SINGLE PURPOSE, TO DESTROY THE WORLD OF MEN. THEY WILL BE HERE BY NIGHTFALL.' ,
                        'THEY WERE ONCE MEN. GREAT KINGS OF MEN. THEN SAURON THE DECEIVER GAVE TO THEM NINE RINGS OF POWER. BLINDED BY THEIR GREED, THEY TOOK THEM WITHOUT QUESTION, ONE BY ONE FALLING INTO DARKNESS. NOW THEY ARE SLAVES TO HIS WILL. THEY ARE THE NAZGUL, RINGWRAITHS, NEITHER LIVING NOR DEAD. AT ALL TIMES THEY FEEL THE PRESENCE OF THE RING, DRAWN TO THE POWER OF THE ONE. THEY WILL NEVER STOP HUNTING YOU.']
                random_item = random.choice(list)
                comment.reply(random_item)
                comment_replied_to.append(comment.id)

                with open("comment_replied_to.txt", "a") as f:
                    f.write(comment.id + "\n")
    print("sleeping for 10 seconds")
    time.sleep(10)


def get_saved_comments():
    if not os.path.isfile("comment_replied_to.txt"):
        comment_replied_to = []
    else:
        with open("comment_replied_to.txt", "r") as f:
            comment_replied_to = f.read()
            comment_replied_to = comment_replied_to.split("\n")
    return comment_replied_to

r = bot_login()
comment_replied_to = get_saved_comments()
while True:
    run_bot(r, comment_replied_to)
